### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by as-cii** [captr/captr-web#2]
There are a few things that I believe we should put inside the README:
- [ ] [Live Demo](http://captr.io)
- [ ] Concept
- [ ] License Summary

Until we decide and set up our development environment and architecture, that's it for me.

/cc: @exalted

**Comment by exalted** [comment]
Huh?! I am confused… _It_?

**Comment by as-cii** [comment]
The issue name is: `Improve README.md` :smile:

**Comment by exalted** [comment]
True!

On Sunday, February 2, 2014, Antonio Scandurra notifications@github.com
wrote:

> The issue name is: Improve README.md [image: :smile:]
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/captr/captr-web/issues/2#issuecomment-33904988
> .

## 

Ali

**Comment by exalted** [comment]
I will take care of that stuff sooner than later.
